# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ $.Values.postgres.serviceName }}
#   namespace: {{ $.Release.Namespace }}
# spec:
#   selector: 
#     app: postgres
#   ports:
#     - name: postgres
#       port: {{ $.Values.postgres.containerPort }}
#       targetPort: {{ $.Values.postgres.containerPort }}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ $.Values.api.serviceName }}
#   namespace: {{ $.Release.Namespace }}
# spec:
#   selector: 
#     app: api
#   ports:
#     - name: api
#       port: {{ $.Values.api.containerPort }}
#       targetPort: {{ $.Values.api.containerPort }}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ $.Values.frontend.serviceName }}
#   namespace: {{ $.Release.Namespace }}
# spec:
#   selector: 
#     app: frontend
#   ports:
#     - name: frontend
#       port: {{ $.Values.frontend.containerPort }}
#       targetPort: {{ $.Values.frontend.containerPort }}
